version: '3.8'

services:
  american_school_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: american_school_app
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - default
      - db_network

  american_school_web:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    container_name: american_school_web
    restart: unless-stopped
    ports:
      - "8081:80" # Expone el puerto 8081 al host VPS
    depends_on:
      - american_school_app
    networks:
      - default

networks:
  default:
  db_network:
    external: true
    name: automation-stack_internal
